#!/usr/bin/env python3
"""AI Art Generator — DeepSeek prompt + SD 1.5 image gen + Telegram delivery."""

import os
import sys
import json
import time
import hashlib
from datetime import datetime
from pathlib import Path

GALLERY = Path(os.environ.get("HERMES_GALLERY", os.path.expanduser("~/.hermes/gallery")))
GALLERY.mkdir(parents=True, exist_ok=True)

PYTHON = r"C:\Users\ViV\AppData\Local\Programs\Python\Python312\python.exe"


def _clean_env():
    """Return an environment for the SD subprocess with PYTHONPATH stripped.

    Without this, a caller's virtualenv (e.g. the Hermes agent venv) leaks its
    site-packages into the Python 3.12 subprocess, and numpy/torch pick up the
    wrong (cp311) compiled extensions, failing with
    'No module named numpy._core._multiarray_umath'.
    """
    env = os.environ.copy()
    env.pop("PYTHONPATH", None)
    return env


PROMPTS = [
    'A cyberpunk city at night, neon lights reflecting in rain puddles, ultra detailed',
    'A mystical forest with glowing mushrooms and fireflies, fantasy art',
    'An astronaut riding a horse on Mars, photorealistic, cinematic lighting',
    'A steampunk airship floating above Victorian London at sunset',
    'A serene Japanese garden with cherry blossoms and a koi pond, watercolor style',
    'A dragon perched on a mountain peak, epic fantasy, dramatic clouds',
    'A cozy cabin in the woods during winter, warm lights in the windows, snow falling',
    'An underwater city with bioluminescent creatures, deep ocean, ethereal',
    'A phoenix rising from flames, digital art, vibrant orange and gold',
    'A futuristic laboratory with holographic displays, sci-fi, blue lighting',
    'A lone wolf howling at a full moon, silhouette, starry night sky',
    'A pirate ship sailing through stormy seas, dramatic lighting, oil painting',
    'A crystal cave with rainbow refractions, magical atmosphere, fantasy',
    'A robot tending a garden of flowers, heartwarming, Pixar style',
    'A desert oasis at twilight, palm trees, reflection in still water',
]

def generate_prompt():
    """Pick a random creative prompt — no API needed."""
    import random
    prompt = random.choice(PROMPTS)
    return prompt


def generate_image(prompt, filename, steps=20, guidance_scale=7.5, width=768, height=448):
    """Generate image using SD 1.5 via subprocess to avoid VRAM conflicts.

    All generation parameters are exposed so the server (or a config file) can
    drive them. The subprocess isolates the model load so it never contends
    with other processes (e.g. the local LLM) for the GPU.
    """
    import subprocess
    script = f"""
import torch, os
from diffusers import StableDiffusionPipeline
os.environ['HF_HUB_DISABLE_SYMLINKS_WARNING'] = '1'
pipe = StableDiffusionPipeline.from_pretrained(
    'sd-legacy/stable-diffusion-v1-5',
    torch_dtype=torch.float16,
    safety_checker=None,
)
pipe = pipe.to('cuda')
pipe.enable_attention_slicing()
image = pipe({json.dumps(prompt)}, num_inference_steps={steps}, guidance_scale={guidance_scale}, width={width}, height={height}).images[0]
image.save(r'{filename}')
print('OK')
"""
    result = subprocess.run(
        [PYTHON, "-c", script],
        capture_output=True, text=True, timeout=300,
        env=_clean_env(),
    )
    return "OK" in result.stdout


def watermark_image(path):
    """Add 'Generated by Local AI' watermark to an image."""
    from PIL import Image, ImageDraw, ImageFont
    img = Image.open(path).convert("RGBA")
    overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    try:
        font = ImageFont.truetype("C:/Windows/Fonts/consola.ttf", 18)
    except OSError:
        font = ImageFont.load_default()
    text = "Generated by Local AI"
    bbox = draw.textbbox((0, 0), text, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    pad = 12
    x, y = pad, img.height - th - pad - 6
    draw.rectangle([x-6, y-4, x+tw+6, y+th+4], fill=(0, 0, 0, 160))
    draw.text((x, y), text, fill=(255, 255, 255, 200), font=font)
    img = Image.alpha_composite(img, overlay).convert("RGB")
    img.save(path)
    print(f"  Watermarked: {path}")


def generate():
    """Full generation pipeline: prompt → image → metadata."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    prompt = generate_prompt()
    safe_name = hashlib.md5(prompt.encode()).hexdigest()[:8]
    filename = GALLERY / f"art_{timestamp}_{safe_name}.png"

    print(f"Prompt: {prompt}")
    print(f"Generating image...")

    success = generate_image(prompt, str(filename))

    if success:
        # Apply watermark before saving metadata
        watermark_image(str(filename))
        meta = {
            "timestamp": timestamp,
            "prompt": prompt,
            "style": "SD 1.5",
            "file": filename.name,
        }
        with open(GALLERY / "index.json", "a") as f:
            f.write(json.dumps(meta) + "\n")
        print(f"Saved: {filename}")
        return prompt, str(filename)
    else:
        print("Generation failed")
        return None, None


def _convert_to_raw(image_path):
    """Convert a single PNG to RGB565 and refresh latest.rgb565 for the P4 panel.

    Uses convert_to_raw.py (which lives alongside this file in both the repo and
    the deployed scripts dir). Loaded via importlib so it works regardless of
    the subprocess working directory.
    """
    import importlib.util
    conv_path = Path(__file__).resolve().parent / "convert_to_raw.py"
    spec = importlib.util.spec_from_file_location("convert_to_raw", conv_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.convert_to_raw(Path(image_path))


def generate_one(prompt, steps=20, guidance_scale=7.5, width=768, height=448):
    """Generate a single image from an explicit prompt + params (server path).

    Unlike generate(), this takes the prompt from the caller instead of picking
    a random one, and it returns a plain dict so a caller (the HTTP server) can
    consume the result without parsing stdout. Returns:
        {"ok": bool, "file": name, "prompt": str, "error": str}
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = hashlib.md5(prompt.encode()).hexdigest()[:8]
    filename = GALLERY / f"art_{timestamp}_{safe_name}.png"

    success = generate_image(prompt, str(filename), steps, guidance_scale, width, height)
    if not success:
        return {"ok": False, "error": "generation failed", "prompt": prompt}

    watermark_image(str(filename))
    meta = {
        "timestamp": timestamp,
        "prompt": prompt,
        "style": "SD 1.5",
        "file": filename.name,
        "steps": steps,
        "width": width,
        "height": height,
    }
    with open(GALLERY / "index.json", "a") as f:
        f.write(json.dumps(meta) + "\n")

    # Refresh the P4 panel's latest.rgb565 framebuffer from this new image.
    try:
        _convert_to_raw(str(filename))
    except Exception as exc:  # noqa: BLE001
        # Raw conversion is best-effort; never fail the job over it.
        print(f"raw conversion skipped: {exc}")

    return {"ok": True, "file": filename.name, "prompt": prompt, "meta": meta}


if __name__ == "__main__":
    # Server subprocess mode: `art_generator.py --one '<json>'`
    # Prints RESULT:<json> so the HTTP server can parse the outcome cleanly.
    if len(sys.argv) >= 3 and sys.argv[1] == "--one":
        params = json.loads(sys.argv[2])
        result = generate_one(
            params.get("prompt", ""),
            params.get("steps", 20),
            params.get("guidance_scale", 7.5),
            params.get("width", 768),
            params.get("height", 448),
        )
        print("RESULT:" + json.dumps(result))
        sys.exit(0)

    prompt, path = generate()
    if prompt:
        print(f"\nDONE: {path}")
        print(f"PROMPT: {prompt}")
        # Signal for Telegram delivery
        print("MEDIA:" + path)
        # Convert to raw RGB565 for P4 panel
        import subprocess
        subprocess.run([PYTHON, os.path.expanduser("~/.hermes/scripts/convert_to_raw.py")], timeout=30)
        print("RAW: converted")

    # Cleanup images older than 24 hours
    cutoff = time.time() - 86400
    deleted = 0
    for f in sorted(GALLERY.glob("*.png")):
        if f.stat().st_mtime < cutoff:
            f.unlink()
            # Also delete corresponding raw file
            raw = GALLERY / "raw" / (f.stem + ".rgb565")
            if raw.exists():
                raw.unlink()
            deleted += 1
    
    # Prune index.json entries for deleted files
    index_path = GALLERY / "index.json"
    if index_path.exists():
        existing_pngs = {f.name for f in GALLERY.glob("*.png")}
        kept = []
        for line in index_path.read_text().strip().split("\n"):
            if line:
                try:
                    meta = json.loads(line)
                    if meta.get("file", "") in existing_pngs:
                        kept.append(line)
                except json.JSONDecodeError:
                    pass
        index_path.write_text("\n".join(kept) + "\n" if kept else "")
    
    if deleted:
        print(f"CLEANUP: removed {deleted} old images")
